domain: raalt7.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://raalt7.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /odin_recipes/      # place folder name if the site is served in a subfolder
